### ISSUE TITLE
Have a read-only editor window when viewing pastes

### ISSUE THREAD

**Issue by clrxbl** [lucko/paste#11]
This is especially an issue on mobile. If you open a paste on mobile, your keyboard will likely pop up every time you try to scroll.

**Comment by lucko** [comment]
It seems fine for me on mobile?

https://gfycat.com/reflectingspottedfairybluebird

I can scroll either by dragging the text area around or using the scrollbar on the right.

**Comment by clrxbl** [comment]
https://gfycat.com/terrifictiredgangesdolphin
A raw button technically solves the issue but isn't too pleasant.

**Comment by lucko** [comment]
Ok lol, yeah I see, that's horrible.

I'll see what I can do :)

**Comment by lucko** [comment]
ed7f8e5bddc763e6ad2f5799f98a0e319320018a

Could you let me know if that's any better? :)

**Comment by clrxbl** [comment]
Unfortunately this still opens the editor. It just prevents me from adding new text.

**Comment by lucko** [comment]
Dug out an old Android phone and was able to reproduce - latest fix seems to resolve it 😃 could you give it another go?

**Comment by clrxbl** [comment]
Issue seems to be resolved.
![image](https://user-images.githubusercontent.com/28601081/151463902-005e7f87-60a8-4ecd-8082-25e69f0ea8e6.png)
Unrelated nitpick; It would be nice to be able to right click on a selected piece of text and Google things.

**Comment by lucko** [comment]
Awesome :)

565fcbe63022f5270472f63561cd18652d9a8a97 should do that - assuming your browser (or maybe its OS dependant?) supports it - it's there for me

<img width="463" alt="Screenshot 2022-01-28 at 00 09 20" src="https://user-images.githubusercontent.com/8352868/151464079-4222e0c7-ca3f-4452-8a47-4acc2ea65e21.png">

Failing that, I guess the contextmenu could be re-added with a action for Googling

**Comment by clrxbl** [comment]
> Awesome :)
> 
> [565fcbe](https://github.com/lucko/paste/commit/565fcbe63022f5270472f63561cd18652d9a8a97) should do that - assuming your browser (or maybe its OS dependant?) supports it - it's there for me
> 
> <img alt="Screenshot 2022-01-28 at 00 09 20" width="463" src="https://user-images.githubusercontent.com/8352868/151464079-4222e0c7-ca3f-4452-8a47-4acc2ea65e21.png">
> 
> Failing that, I guess the contextmenu could be re-added with an action for Googling

That commit is why I figured I'd mention it.
It doesn't work on Chrome at least.

![image](https://user-images.githubusercontent.com/28601081/151464263-b1b1126e-8d32-4c19-97e5-1bd7f1bb5584.png)

**Comment by lucko** [comment]
98b880773ea11bd75bb9ad1f9a1fc40918dcc1cc

<img width="425" alt="Screenshot 2022-01-28 at 00 57 14" src="https://user-images.githubusercontent.com/8352868/151468420-6cf91bf9-a2e3-492d-a012-140910e37996.png">
