### ISSUE TITLE
Netcat / easier command line pasting

### ISSUE THREAD

**Issue by clrxbl** [lucko/paste#8]
Love using pastes.dev, but would love to see the ability from e.g. https://termbin.com/ to netcat content to pastes.dev.
I guess an alternative to this would be sending an HTTP request to the pastes.dev API which I guess I could create an alias for, but something like netcat is a lot easier.

**Comment by lucko** [comment]
This is a nice idea, thanks!

Functionality to support this has been added in:

* https://github.com/lucko/paste-netcat/commit/8f7bce0d6429ff8f79f0ce2d555c1358767f93dd
* https://github.com/lucko/bytebin/commit/5150d0fa85f8f564158e7427d783dab754069e90

You can now upload as below:

```shell
# Pipe in some output from any command
> echo "Hello world" | nc nc.pastes.dev 1337

# Upload the contents of a file
> cat example123.txt | nc nc.pastes.dev 1337
```

Bit of a childish port number but I thought it'd be easier to remember 😛

See https://github.com/lucko/paste-netcat/ for more info on the implementation. I thought it was better to have a separate service that handles the netcat connections and proxies them to the normal HTTP storage API (bytebin). You could even standup your own instance of paste-netcat (e.g. inside a firewall) but still proxy out to the pastes.dev service.

In theory it supports the same content size limits as bytebin - currently configured to a max of 10mb post-gzip. The paste-netcat server handles compression before forwarding the request on. All of which means it should be able to handle reasonably large plaintext files with no issue.

I've also updated the readme with this info :)

Thanks again!

**Comment by clrxbl** [comment]
Hm, nc.pastes.dev doesn't seem to be working for me?

```
/tmp/server via ☕ v17.0.1
❯ cat paper.yml | nc nc.pastes.dev 1337

/tmp/server via ☕ v17.0.1 took 30s
❯
```

**Comment by lucko** [comment]
Ah! I was testing with netcat on macOS, which has some subtle differences compared with other versions (e.g. on Linux machines)

Should be fixed by https://github.com/lucko/paste-netcat/commit/8673ada05839a5b05da3ce697238bf6aa1e85fbb :)

Let me know if that works

**Comment by clrxbl** [comment]
Works! Another suggestion would be to add the ability to specify a language for syntax highlighting until there's some auto detection.

e.g. netcat to nc.pastes.dev/yaml for YAML

**Comment by lucko** [comment]
Sweet!

Unfortunately netcat only works with hostnames & ports, not URLs - that's a HTTP thing.

Only options are:
1. more subdomains (bit of a pain)
2. more ports (hard to remember)
3. some sort of header in the submitted content - but that that point you're better off using curl

```shell
echo "test: 123" | curl -d @- -H 'Content-Type: text/yaml' https://api.pastes.dev/post
```

Auto-detection is also a bit tricky, but I'll elaborate more on that another time, on the other issue.

**Comment by clrxbl** [comment]
> Sweet!
> 
> Unfortunately netcat only works with hostnames & ports, not URLs - that's a HTTP thing.
> 
> Only options are:
> 
> 1. more subdomains (bit of a pain)
> 2. more ports (hard to remember)
> 3. some sort of header in the submitted content - but at that point you're better off using curl
> 
> ```shell
> echo "test: 123" | curl -d @- -H 'Content-Type: text/yaml' https://api.pastes.dev/post
> ```
> 
> Auto-detection is also a bit tricky, but I'll elaborate more on that another time, on the other issue.

Subdomains seem somewhat doable? Because you can have wildcard subdomains & SSL records.
Something like yaml.nc.pastes.dev could work.

**Comment by lucko** [comment]
The server doesn't know which subdomain the request was made from.

This is only possible for HTTP servers because of the `Host` header - whereas netcat does the DNS resolution on the client side and then opens a direct TCP connection.

**Comment by clrxbl** [comment]
> The server doesn't know which subdomain the request was made from.
> 
> This is only possible for HTTP servers because of the `Host` header - whereas netcat does the DNS resolution on the client side and then opens a direct TCP connection.

Ahhhhh, okay. Makes sense.
